services:
  martin:
    image: ghcr.io/maplibre/martin:v0.15.0
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@ar-db/ar_climate_data
    volumes:
      - ./config/martin-config.yaml:/etc/martin/martin-config.yaml
    command: -c /etc/martin/martin-config.yaml
    depends_on:
      - ar-db
  var-api:
    build:
      context: .
      dockerfile: docker/var-api.Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@ar-db/ar_climate_data
      - MAPTILER_API_KEY=${MAPTILER_API_KEY}
    depends_on:
      - ar-db
  ar-db:
    build:
      context: .
      dockerfile: docker/ar-db.Dockerfile
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./data:/data
    environment:
      - POSTGRES_DB=ar_climate_data
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
